---
platforms:
  ubuntu1804:
    test_targets:
    - "@rules_foreign_cc_tests//:tests"
  ubuntu1604:
    test_targets:
    - "@rules_foreign_cc_tests//:tests_no_synthetic"
  macos:
    test_targets:
    - "@rules_foreign_cc_tests//:cmake_tests"
  windows:
    test_flags:
    - "--action_env=MSBuildExtensionsPath"
    - "--action_env=VCTargetsPath"
    - "--test_env=MSBuildExtensionsPath"
    - "--test_env=VCTargetsPath"
    test_targets:
    - "@rules_foreign_cc_tests//:win_tests"
